### ISSUE TITLE
"TypeError: 'type' object is not subscriptable" on build

### ISSUE THREAD

**Issue by cccaballero** [stronnag/wayfarer#6]
Using Ubuntu 22.04, the `ninja install -C build` command outputs:

```
ninja: Entering directory `build'
[2/22] Generating data/blueprints with a custom command
FAILED: data 
/home/cccaballero/Software/wayfarer/build/subprojects/blueprint-compiler/blueprint-compiler batch-compile data/. ../data ../data/wayfarer.blp
Traceback (most recent call last):
  File "/home/cccaballero/Software/wayfarer/build/subprojects/blueprint-compiler/blueprint-compiler", line 38, in <module>
    from blueprintcompiler import main
  File "/home/cccaballero/Software/wayfarer/subprojects/blueprint-compiler/blueprintcompiler/main.py", line 27, in <module>
    from . import interactive_port, parser, tokenizer
  File "/home/cccaballero/Software/wayfarer/subprojects/blueprint-compiler/blueprintcompiler/interactive_port.py", line 25, in <module>
    from . import decompiler, parser, tokenizer
  File "/home/cccaballero/Software/wayfarer/subprojects/blueprint-compiler/blueprintcompiler/decompiler.py", line 25, in <module>
    from .gir import *
  File "/home/cccaballero/Software/wayfarer/subprojects/blueprint-compiler/blueprintcompiler/gir.py", line 69, in <module>
    _available_namespaces: list[tuple[str, str]] = []
TypeError: 'type' object is not subscriptable
[4/22] Compiling Vala source ../src/gst-recording.vala ../src/recman.vala ../src/utils.vala ../src/x...c/wayfarer.vala ../src/selection.vala ../src/pipeline.vala ../src/encoders.vala ../src/settings.vala
ninja: build stopped: subcommand failed.
```

**Comment by stronnag** [comment]
Builds fine here on Ubuntu 22.04. Probably some `blueprint`  missing. Some clues in https://jwestman.pages.gitlab.gnome.org/blueprint-compiler/packaging.html#gobject-introspection, possibly one or more of  `gobject-introspection`,  `python3-gi`.
